language: node_js
node_js:
- '0.11'
deploy:
  provider: heroku
  api_key:
    secure: MeW7WIMdJZvmZhfM+wud1/8u/CtRhvpmsxQEz+6xUIGleNbS4mnJrCX2rUfctGNoRJ+3ycnmU1zpgyCRF8SZ2n1gQnHQCIMIqXV/2ScnYgDQWLBZmnl5PJsH870q+488lV0FEREXN4AzOQbWOGUELQoFuYdKqS474H8KV53yeIQ=
  app: ux-hubot
  on:
    repo: keymholio/uxhubot
